CREATE TABLE usuarios (
id BIGSERIAL PRIMARY KEY,
nome VARCHAR(255) NOT NULL,
email VARCHAR(255) UNIQUE NOT NULL,
senha VARCHAR(255) NOT NULL,
funcao_usuario VARCHAR(50),
data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);